FROM alpine:3.7
ENV PYTHONUNBUFFERED 1

ADD requirements.txt /code/

RUN apk add --no-cache python2 py2-pip py-gevent && \
    pip install -r /code/requirements.txt

ADD . /code/
WORKDIR /code

EXPOSE 8000
CMD ["python", "run.py"]
